spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taldaf-commerce
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
