spring:
  datasource:
    url: {{dburl}}
    username: {{dbusername}}
    password: {{dbpassword}}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


# 서버 설정
server:
  tomcat:
    access log:
      enabled: true
      directory: /opt/backend/log/access
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: '%{X-Forwarded-For}i %h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D ms'
      rotate: true

# 로깅 설정
logging:
  file:
    name: /opt/backend/log/logback
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n'
  logback:
    rolling policy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      file-name-pattern: 'logs/application.%d{yyyy-MM-dd}.%i.log.gz'
